version: '3.8'

services:
  web:
    container_name: querydb
    build:
      context: .
    ports:
      - "8002:8001"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: American_Gut_Project_PRJEB11419
      DB_USER: mysql
      DB_PASSWORD: mspgnuig
      DB_PORT: 3307 

  db:
    image: mysql:8.0
    container_name: mysql-db
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: American_Gut_Project_PRJEB11419
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mspgnuig
    ports:
      - "3307:3306"
    volumes:
      # Mount the database dump into the initialization folder
      - ./american_gut_database.sql:/docker-entrypoint-initdb.d/american_gut_database.sql
    restart: always
  # web:
  #   container_name: querydb
  #   build:
  #     context: .
  #   ports:
  #     - "8001:8001"
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   environment:
  #     DB_HOST: db
  #     DB_NAME: American_Gut_Project_PRJEB11419
  #     DB_USER: mysql
  #     DB_PASSWORD: mspgnuig

  # db:
  #   image: mysql:8.0
  #   container_name: mysql-db
  #   platform: linux/amd64
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: American_Gut_Project_PRJEB11419
  #     MYSQL_USER: mysql
  #     MYSQL_PASSWORD: mspgnuig
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - ./american_gut_database.sql:/docker-entrypoint-initdb.d/american_gut_database.sql
  #   healthcheck:
  #     test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root --password=root || exit 1"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 3
  #   restart: always